version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  utils:
    build:
      context: ./utils
  locust:
    build:
      context: ./locust
    ports:
      - "8089:8089"
  python-server:
    build:
      context: ./python-server
    restart: always
    volumes:
      - ./python-server:/app
    ports:
      - "8000:8000"
  go-server:
    build:
      context: ./go-server
    restart: always
    volumes:
      - ./go-server:/app
    ports:
      - "8001:8001"
